### ISSUE TITLE
Back 03 - Yo como usuario puedo registrar mis servicios

### ISSUE THREAD

**Issue by rafmanrique** [rafmanrique/onclickservice-ocs-backend#5]
- [x] Crear tabla para Registro de Servicio
- [x] Crear POST de registro de servicio
- [x]  Validar la independencia de los demas registros (unico por usuario) pero misma categoria

**Comment by rodriguezandresed** [comment]
closed on c69acb98e8e9a26efaff2c418eca0247fa3781f2
